name: Integrations pipeline

on: 
    push: 
        branches: [ main]
    pull_request:
        branches: [ main]

jobs: 
    frontend:
        name: Build frontend
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend

        steps: 
          - name: Checkout repo
            uses: actions/checkout@v3

          - name: Setup Node.js
            uses: actions/setup-node@v3
            with:
                 node-version: 20
         
          - name: Install dependencies
            run: npm install

        
    backend:
        name: Build backend
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend
        
        steps:
          - name: Checkout repo
            uses: actions/checkout@v3

          - name: Setup Node.js
            uses: actions/setup-node@v3
            with: 
                node-version: 20
         
          - name: Install dependencies
            run: npm install

          

            

